### ISSUE TITLE
Implement Affine gap measure 

### ISSUE THREAD

**Issue by alihitawala** [kvpradap/py_stringmatching#12]

**Comment by kvpradap** [comment]
pulled in the request and updated xrange to _range.

**Comment by kvpradap** [comment]
@alihitawala why are the gap costs set to negative?. I see that needleman wunsch, smith waterman etc. uses positive gap costs.

I think we should follow a uniform policy. I suggest the gap costs be positive.

Further, is there a reason why needleman-wunsch, smith waterman uses "int" gap costs but affine gap uses float gap cost?. If there is no reason, then uniformly we should just use float.

**Comment by alihitawala** [comment]
On where should I commit this change? Like master or some branch live right now?
And also where should I commit changes for Needleman and other issues? develop branch can't be used as of now.

**Comment by alihitawala** [comment]
I have created a new branch to deal with the affine gap score issue.

**Comment by alihitawala** [comment]
@kvpradap  Why are the comments saying to be deleted? I just have to change the implementation a bit, right?

**Comment by kvpradap** [comment]
@alihitawala I have commented affine gap implementation in the main branch (I just left it as a reference implementation). As I mentioned yesterday,  there should be two things done while you branch and rewrite affine gap:

1) Delete the commented affine gap portion in simfunctions.py
2) Have a new version of affine gap  

I see that, you have you have done the above in feature_affine_gap branch. I will review them and merge the request.

**Comment by kvpradap** [comment]
@alihitawala 
The changes look fine.
I made the following changes:
1) Updated comments for the affine function
2) Updated simfunctions.rst file to generate documentation for affine
3) Updated import statements in test_simfunctions.py

I merged the pull request.
