### ISSUE TITLE
Implement soft tfidf

### ISSUE THREAD

**Issue by kvpradap** [kvpradap/py_stringmatching#16]
Implement soft tfidf as given in DI book.
@alihitawala Pl. use feature_softtfidf branch

**Comment by alihitawala** [comment]
@kvpradap 
What's the default sim measure to use between tokens in this algorithm? and I am assuming that the API will be different from TFIDF in the sense that this will take a threshold too to decide if a token is similar to other tokens in the other bag?

**Comment by alihitawala** [comment]
I have one implementation ready but would like to go through the implementation before going forward. Let's go through this on Monday.

**Comment by kvpradap** [comment]
@alihitawala  The API will be similar to TFIDF, except that softtfidf will have an addition argument for a  function. The function will take in two strings and return True if they are similar and False if they are not.

Anyways, we can discuss more about it on Monday.

**Comment by alihitawala** [comment]
OK this is good, this means we don't have to deal with sim function and threshold ourselves. But should I give a default implementation in case user doesn't provide one? What will it be in that case?

**Comment by kvpradap** [comment]
Yes, we should give a default implementation. 

I think we can have sim_ident (i.e to true if the tokens are same) as the default implementation.

**Comment by kvpradap** [comment]
![20160215_164043](https://cloud.githubusercontent.com/assets/9136120/13062303/3e15ae30-d403-11e5-955d-a773575f1a51.jpg)
